spring.application.name=AlokSpringCRUD
spring.datasource.url=jdbc:postgresql://localhost:5432/webalok
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver